"""refactor label model

Revision ID: 423dad6ecfde
Revises: 736f73372987
Create Date: 2023-07-14 17:01:33.921653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423dad6ecfde'
down_revision = '736f73372987'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_association', sa.Column('note_id', sa.BigInteger(), nullable=False))
    op.alter_column('label_association', 'label_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('label_association', 'user_id')
    # ### end Alembic commands ###


def downgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_association', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.alter_column('label_association', 'label_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('label_association', 'note_id')
    # ### end Alembic commands ###

