"""label association

Revision ID: 736f73372987
Revises: 781746bfa3f3
Create Date: 2023-07-14 16:06:52.500237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736f73372987'
down_revision = '781746bfa3f3'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_association',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_association_id'), 'label_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_association_id'), table_name='label_association')
    op.drop_table('label_association')
    # ### end Alembic commands ###

