"""label model

Revision ID: 781746bfa3f3
Revises: f2f6d11e880f
Create Date: 2023-07-14 08:34:37.901404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781746bfa3f3'
down_revision = 'f2f6d11e880f'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_note_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade_label_ms() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'user_id')
    # ### end Alembic commands ###

